# Generated by Django 4.1 on 2023-07-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard_app', '0002_searchhistory_user_delete_userdb_searchhistory_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='dbuserdata',
        ),
    ]
