# Generated by Django 4.1 on 2023-07-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard_app', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterModelTable(
            name='user',
            table='dbuser',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
