# Generated by Django 4.1 on 2023-07-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard_app', '0004_remove_user_email_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='dbusername',
        ),
    ]
