# Generated by Django 4.1 on 2023-07-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard_app', '0005_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BaseUserManger',
        ),
    ]
